apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
    - image: whoami
      docker:
        dockerfile: images/whoami/Dockerfile
deploy:
  helm:
    releases:
      - name: fullstack
        chartPath: chart