apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
    - image: frontend
      docker:
        dockerfile: images/frontend/Dockerfile
      sync: 
        manual:
          - dest: /app
            src: src/frontend/**/*.css
            strip: src/frontend
          - dest: /app
            src: src/frontend/**/*.ts
            strip: src/frontend
          - dest: /app
            src: src/frontend/**/*.tsx
            strip: src/frontend
    - image: api
      docker:
        dockerfile: images/api/Dockerfile
      sync: 
        manual:
          - dest: /app
            src: src/api/**/*.py
            strip: src/api
  local:
    concurrency: 0
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: fullstack
        chartPath: chart
        artifactOverrides:
          APIImage: api
          FrontendImage: frontend
profiles:
  - name: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: images/frontend/Dockerfile.Dev
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: images/api/Dockerfile.Dev
