apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
    - image: frontend
      docker:
        dockerfile: images/frontend/Dockerfile
  local:
    concurrency: 0
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: fullstack
        chartPath: chart
        artifactOverrides:
          FrontendImage: frontend
         