apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
    - image: whoami
      docker:
        dockerfile: images/whoami/Dockerfile
  local:
    concurrency: 0
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: fullstack
        chartPath: chart