apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.POSTGRES_LOCAL_DATA_PATH }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: db
          image: postgres:13
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: {{ required "POSTGRES_PASSWORD is required" .Values.POSTGRES_PASSWORD }} 
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: task-pv-storage

---
apiVersion: v1
kind: Service
metadata:
  name: db-service  
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
