name: GitHub Actions - CI/CD
on: [push, pull_request]
env:
  SKAFFOLD_VERSION: v1.26.1
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: "Prep: Check out repository code"
        uses: actions/checkout@v2
      - name: "Prep: Start minikube"
        run: minikube start
      - name: "Prep: Install skaffold"
        run: |
          curl -Lo skaffold https://github.com/GoogleContainerTools/skaffold/releases/download/${SKAFFOLD_VERSION}/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Build images
        run: skaffold run
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    env: 
      SKAFFOLD_DEFAULT_REPO: ghcr.io/${{ github.repository_owner }}
    steps:
      - name: "Prep: Check out repository code"
        uses: actions/checkout@v2
      - name: "Prep: Install skaffold"
        run: |
          curl -Lo skaffold https://github.com/GoogleContainerTools/skaffold/releases/download/${SKAFFOLD_VERSION}/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Build images
        run: skaffold run
